SELECT TOP 1 country
FROM CLASSES
ORDER BY NUMGUNS DESC

SELECT DISTINCT CLASSES.CLASS
FROM OUTCOMES,SHIPS,CLASSES
WHERE SHIP = NAME AND SHIPS.CLASS = CLASSES.CLASS AND RESULT = 'sunk'

SELECT SHIPS.NAME, CLASSES.CLASS
FROM CLASSES, SHIPS
WHERE CLASSES.CLASS = SHIPS.CLASS AND CLASSES.BORE = 16;

SELECT BATTLE
FROM OUTCOMES,SHIPS,CLASSES
WHERE OUTCOMES.SHIP = SHIPS.NAME AND SHIPS.CLASS = CLASSES.CLASS AND CLASSES.CLASS = 'Kongo'

SELECT SHIPS.CLASS,NAME
FROM SHIPS,CLASSES CL1
WHERE CL1.CLASS = SHIPS.CLASS  AND
CL1.NUMGUNS > ANY(SELECT NUMGUNS FROM CLASSES CL2 WHERE CL2.BORE = CL1.BORE ); 

SELECT s.CLASS, s.NAME FROM SHIPS AS s
WHERE s.CLASS IN (SELECT class FROM CLASSES as old WHERE NUMGUNS >= (SELECT TOP 1 NUMGUNS FROM CLASSES as new WHERE old.BORE = new.BORE ORDER BY NUMGUNS DESC))
ORDER BY s.CLASS ASC
