CREATE TRIGGER bookings_delete 
ON BOOKINGS 
AFTER DELETE 
AS
BEGIN
UPDATE FLIGHTS SET num_pass = num_pass-1 WHERE FNUMBER = (SELECT FLIGHT_NUMBER FROM deleted);
UPDATE AGENCIES SET num_book = num_book-1 WHERE NAME = (SELECT AGENCY FROM deleted);
END