CREATE TRIGGER bookings_update 
ON BOOKINGS 
AFTER UPDATE 
AS
BEGIN
UPDATE FLIGHTS SET num_pass = num_pass+1 WHERE FNUMBER = (SELECT FLIGHT_NUMBER FROM inserted);
UPDATE AGENCIES SET num_book = num_book+1 WHERE NAME = (SELECT AGENCY FROM inserted);
UPDATE FLIGHTS SET num_pass = num_pass-1 WHERE FNUMBER = (SELECT FLIGHT_NUMBER FROM deleted);
UPDATE AGENCIES SET num_book = num_book-1 WHERE NAME = (SELECT AGENCY FROM deleted);
END