SELECT w.BATTLE
FROM (
SELECT BATTLE,COUNT( DISTINCT SHIP) as SHIP_COUNT
FROM OUTCOMES
GROUP BY BATTLE)t
JOIN 
(SELECT BATTLE,COUNT(DISTINCT c.COUNTRY) as COUNTRY_COUNT
FROM OUTCOMES o JOIN  SHIPS s ON
O.SHIP = s.NAME JOIN  CLASSES c ON
s.CLASS = c.CLASS
GROUP BY BATTLE) w
ON t.BATTLE = w.BATTLE
WHERE w.COUNTRY_COUNT >= ANY(

SELECT w.COUNTRY_COUNT
FROM (
SELECT BATTLE,COUNT( DISTINCT SHIP) as SHIP_COUNT
FROM OUTCOMES
GROUP BY BATTLE)t
JOIN 
(SELECT BATTLE,COUNT(DISTINCT c.COUNTRY) as COUNTRY_COUNT
FROM OUTCOMES o JOIN  SHIPS s ON
O.SHIP = s.NAME JOIN  CLASSES c ON
s.CLASS = c.CLASS
GROUP BY BATTLE) w
ON t.BATTLE = w.BATTLE
WHERE t.BATTLE  = 'Guadalcanal') 

AND

t.SHIP_COUNT > ANY (
SELECT t.SHIP_COUNT
FROM (
SELECT BATTLE,COUNT( DISTINCT SHIP) as SHIP_COUNT
FROM OUTCOMES
GROUP BY BATTLE)t
JOIN 
(SELECT BATTLE,COUNT(DISTINCT c.COUNTRY) as COUNTRY_COUNT
FROM OUTCOMES o JOIN  SHIPS s ON
O.SHIP = s.NAME JOIN  CLASSES c ON
s.CLASS = c.CLASS
GROUP BY BATTLE) w
ON t.BATTLE = w.BATTLE
WHERE t.BATTLE  = 'Guadalcanal') 

DELETE FROM OUTCOMES
WHERE BATTLE = (
SELECT BATTLE
FROM OUTCOMES
GROUP BY BATTLE
HAVING COUNT( DISTINCT SHIP) = 2 )

INSERT INTO outcomes VALUES ('Missouri','Surigao Strait', 'sunk'),
('Missouri','North Cape', 'sunk'),
('Missouri','North Atlantic', 'ok');

DELETE FROM OUTCOMES
WHERE SHIP IN (
SELECT SHIP
FROM OUTCOMES
WHERE RESULT = 'sunk'
GROUP BY SHIP
HAVING COUNT(*) >=2)
----------------------------------------
CREATE VIEW v_battle_coutries AS
SELECT DISTINCT b.NAME, c.COUNTRY
FROM BATTLES b JOIN OUTCOMES o ON b.NAME=o.BATTLE JOIN SHIPS s ON o.SHIP=s.NAME JOIN CLASSES c on s.CLASS=c.CLASS 

SELECT DISTINCT bc1.NAME
FROM v_battle_coutries bc1 JOIN v_battle_coutries bc2 ON bc1.NAME=bc2.NAME AND bc1.COUNTRY != bc2.COUNTRY
WHERE bc2.COUNTRY IN (
SELECT bc2.COUNTRY
FROM v_battle_coutries bc1 JOIN v_battle_coutries bc2 ON bc1.NAME=bc2.NAME AND bc1.COUNTRY != bc2.COUNTRY
WHERE bc1.NAME='Guadalcanal') 
AND bc1.COUNTRY IN (
SELECT bc1.COUNTRY
FROM v_battle_coutries bc1 JOIN v_battle_coutries bc2 ON bc1.NAME=bc2.NAME AND bc1.COUNTRY != bc2.COUNTRY
WHERE bc1.NAME='Guadalcanal')
AND bc1.NAME !='Guadalcanal'

----------------------------------------

SELECT c.COUNTRY,COUNT(o.BATTLE) as NUM_BATTLES
FROM CLASSES c LEFT JOIN SHIPS s ON c.CLASS=s.CLASS LEFT JOIN OUTCOMES o ON s.NAME=o.SHIP
GROUP BY COUNTRY