SELECT DISTINCT PRODUCT.MAKER, LAPTOP.SPEED
FROM PRODUCT,LAPTOP
WHERE HD >= 9 AND PRODUCT.MODEL = LAPTOP.MODEL;

(SELECT DISTINCT PRODUCT.MODEL,LAPTOP.PRICE
FROM PRODUCT,LAPTOP
WHERE PRODUCT.MAKER = 'B' AND PRODUCT.MODEL = LAPTOP.MODEL)
UNION
(SELECT DISTINCT PRODUCT.MODEL,PC.PRICE
FROM PRODUCT,PC
WHERE PRODUCT.MAKER = 'B' AND PRODUCT.MODEL = PC.MODEL)
UNION
(SELECT DISTINCT PRODUCT.MODEL,PRINTER.PRICE
FROM PRODUCT,PRINTER
WHERE PRODUCT.MAKER = 'B' AND PRODUCT.MODEL = PRINTER.MODEL);

(SELECT DISTINCT PRODUCT.MAKER
FROM PRODUCT,LAPTOP
WHERE PRODUCT.MODEL = LAPTOP.MODEL)
EXCEPT
(SELECT DISTINCT PRODUCT.MAKER
FROM PRODUCT, PC
WHERE PRODUCT.MODEL =  PC.MODEL);

SELECT HD
FROM PC
GROUP BY HD
HAVING COUNT(CODE)>1;

SELECT DISTINCT p2.MODEL,p1.MODEL
FROM PC AS p2,PC AS p1
WHERE p2.SPEED = p1.SPEED AND p2.RAM = p1.RAM AND p1.MODEL != p2.MODEL AND p1.MODEL > p2.MODEL;

(SELECT DISTINCT maker
FROM product, pc
WHERE pc.model = product.model AND pc.speed>=400)
INTERSECT
(SELECT DISTINCT maker
FROM product, laptop
WHERE product.model=laptop.model AND laptop.speed>=400);



