SELECT m.title, me.name
FROM MOVIE m JOIN MOVIEEXEC me ON m.PRODUCERC# = me.CERT#
WHERE me.NAME = (SELECT me.name FROM MOVIE m JOIN MOVIEEXEC me ON m.PRODUCERC# = me.CERT# WHERE m.TITLE = 'Star Wars' );


SELECT DISTINCT me.name
FROM MOVIEEXEC me JOIN MOVIE m ON m.PRODUCERC# = me.CERT#
WHERE m.TITLE = ANY(SELECT m.TITLE FROM MOVIE m JOIN STARSIN st ON m.TITLE = st.MOVIETITLE WHERE st.STARNAME = 'Harrison Ford');

SELECT DISTINCT m.STUDIONAME as name, st.STARNAME as starname
FROM MOVIE m JOIN STARSIN st ON m.TITLE=st.MOVIETITLE
ORDER BY m.STUDIONAME

SELECT st.starname,me.networth,m.title
FROM (STARSIN st JOIN MOVIE m ON st.MOVIETITLE = m.TITLE ) JOIN MOVIEEXEC me ON m.PRODUCERC# = me.CERT#
WHERE me.NETWORTH = (SELECT TOP 1 me2.NETWORTH FROM MOVIEEXEC me2 ORDER BY me2.NETWORTH DESC);

SELECT ms.NAME, ss.MOVIETITLE
FROM (MOVIESTAR ms LEFT JOIN STARSIN ss  ON  ms.NAME = ss.STARNAME )
WHERE ss.MOVIETITLE IS NULL;




