SELECT *
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS;

SELECT *
FROM SHIPS RIGHT JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS 
ORDER BY SHIPS.NAME ASC;

SELECT CLASSES.country,SHIPS.name
FROM (SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS) LEFT JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP 
WHERE OUTCOMES.RESULT IS NULL
ORDER BY CLASSES.COUNTRY,SHIPS.NAME ASC

SELECT SHIPS.NAME AS 'Ship Name'
FROM CLASSES JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS AND CLASSES.NUMGUNS > 7
WHERE SHIPS.LAUNCHED = 1916 

SELECT ship,BATTLES.name,BATTLES.date
FROM OUTCOMES JOIN BATTLES ON OUTCOMES.BATTLE = BATTLES.NAME AND OUTCOMES.RESULT='sunk'
ORDER BY BATTLES.NAME asc

SELECT SHIPS.name , CLASSES.displacement, SHIPS.launched
FROM CLASSES JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS AND CLASSES.CLASS = SHIPS.NAME

SELECT CLASSES.class, CLASSES.type, CLASSES.country, CLASSES.numguns, CLASSES.bore,CLASSES.displacement
FROM CLASSES LEFT JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS 
WHERE LAUNCHED IS NULL

SELECT SHIPS.name, CLASSES.displacement, CLASSES.numguns,OUTCOMES.result
FROM (CLASSES JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS) JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP AND OUTCOMES.BATTLE = 'North Atlantic'